ingredientes = {
    'pechugas de pollo': 200,
    'cebolla grande': 200,
    'dientes de ajo': 15,
    'lata de leche de coco': 400,
    'cucharadas de pasta de curry': 30,
    'Aceite de coco': 30,
    'Sal': 5,
    'Pimienta': 5,
    'tomates maduros': 200,
    'cebolla': 200,
    'zanahoria': 200,
    'litro de caldo de verduras': 1000,
    'Aceite de oliva': 30,
    'pasta': 250,
    'panceta o bacon': 200,
    'yemas de huevo': 50,
    'taza de queso parmesano rallado': 100,
    'Pimienta negra molida': 5,
    'pechugas de pollo cocidas y desmenuzadas': 200,
    'lata de salsa de enchilada roja': 200,
    'lata de frijoles refritos': 400,
    'taza de queso cheddar rallado': 100,
    'taza de crema agria': 250,
    'Tortillas de maíz': 200,
    'Aceite vegetal': 30,
    'filetes de salmón fresco': 200,
    'limón': 200,
    'dientes de ajo picados': 15,
    'ramitas de romero fresco': 15,
    'lechuga romana': 150,
    'pechuga de pollo a la parrilla': 200,
    'tazas de crutones': 200,
    'taza de aderezo César': 250,
    'kg de carne de cerdo en trozos': 1000,
    'cebolla blanca picada': 200,
    'lima': 200,
    'tortillas de maíz': 200,
    'taza de cilantro fresco picado': 100,
    'tazas de arroz': 400,
    'kg de muslos de pollo': 1000,
    'cebolla picada': 200,
    'taza de guisantes congelados': 200,
    'taza de zanahorias en cubos': 200,
    'taza de caldo de pollo': 250,
    'tazas de café espresso': 400,
    'paquete de bizcochos de soletilla': 200,
    'tazas de mascarpone': 400,
    'huevos': 50,
    'tazas de azúcar': 400,
    'cucharadas de cacao en polvo': 30,
    'tazas de zanahoria rallada': 400,
    'tazas de harina de trigo': 400,
    'taza de aceite vegetal': 250,
    'cucharaditas de canela molida': 5,
    'cucharaditas de polvo de hornear': 5,
    'cucharadita de sal': 5,
    'taza de nueces picadas': 100,
    'taza de mantequilla derretida': 200,
    'cucharadita de extracto de vainilla': 5,
    'taza de cacao en polvo': 100,
    'taza de nueces picadas (opcional)': 100,
    'taza de avena': 200,
    'taza de azúcar moreno': 200,
    'taza de pasas': 200,
    'huevo': 50,
    'cucharadita de bicarbonato de sodio': 5,
    'taza de leche entera': 250,
    'lata de leche evaporada': 400,
    'lata de leche condensada': 400,
    'taza de crema para batir': 500,
    'taza de harina de trigo': 200,
    'taza de leche': 250,
    'cucharadita de polvo de hornear': 5,
    'pizca de sal': 1,
    'kg de tomates maduros': 1000,
    'taza de caldo de verduras': 250,
    'cucharada de aceite de oliva': 15,
    'cucharadita de azúcar': 5,
    'taza de crema de leche': 250,
    'paquete de pasta fettuccine': 250,
    'pechugas de pollo en trozos': 200,
    'taza de mantequilla': 200,
    'manzanas': 200,
    'plátanos': 150,
    'naranjas': 150,
    'peras': 150,
    'tazas de fresas': 200,
    'taza de uvas': 150,
    'taza de jugo de naranja': 250,
    'cucharada de miel': 15,
    'taza de arroz arborio': 200,
    'taza de champiñones picados': 200,
    'taza de vino blanco': 250,
    'taza de caldo de verduras caliente': 250,
    'cucharada de mantequilla': 15,
    'base de pizza': 200,
    'taza de salsa de tomate': 250,
    'taza de queso mozzarella rallado': 200,
    'tomates cherry cortados por la mitad': 150,
    'taza de hojas de albahaca fresca': 100,
    'tazas de lentejas secas': 400,
    'zanahorias en cubos': 200,
    'apio picado': 200,
    'litros de caldo de verduras': 1000,
    'cucharadita de comino molido': 5,
    'cucharadita de pimentón': 5,
    'hojas de lechuga romana': 100,
    'taza de croutons': 100,
    'cucharadita de mostaza dijon': 5,
    'cucharadita de ajo picado': 5,
    'cucharada de jugo de limón': 15,
    'cucharadita de salsa Worcestershire': 5,
    'taza de aceite de oliva': 250,
    'taza de arroz de sushi': 200,
    'taza de agua': 250,
    'cucharada de azúcar': 15,
    'taza de vinagre de arroz': 250,
    'hojas de nori': 100,
    'palta en tiras': 150,
    'pepinillos en tiras': 150,
    'sésamo tostado': 50,
    'salsa de soja': 250,
    'wasabi': 5,
    'jengibre encurtido': 50,
    'pechugas de pollo deshuesadas y sin piel': 200,
    'taza de cebolla picada': 200,
    'cucharadita de chile en polvo': 5,
    'taza de queso rallado': 100,
    'taza de mantequilla sin sal derretida': 200,
    'taza de chips de chocolate': 100,
    'paquete de láminas de lasaña': 200,
    'taza de carne molida de res': 200,
    'taza de carne molida de cerdo': 200,
    'taza de queso ricotta': 100,
    'cucharadita de orégano seco': 5,
    'cucharadita de albahaca seca': 5,
    'tazas de crema para batir': 500,
    'tazas de leche entera': 250,
    'taza de carne picada': 200,
    'pimiento rojo picado': 150,
    'taza de aceitunas verdes picadas': 100,
    'cucharadita de ají molido': 5,
    'taza de caldo de carne': 250,
    'tazas de masa para empanadas': 400,
    'taza de champiñones frescos en rodajas': 200,
    'tazas de caldo de verduras caliente': 250,
    'plátanos en rodajas': 150,
    'manzanas en cubos': 200,
    'naranjas en gajos': 150,
    'kiwis pelados y cortados en rodajas': 150,
    'taza de fresas cortadas por la mitad': 100,
    'taza de uvas sin semillas': 150,
    'taza de piña en trozos': 200,
    'taza de melón en cubos': 200,
    'cucharadita de jugo de limón': 5,
    'levadura seca activa': 15,
    'taza de agua tibia': 250,
    'taza de champiñones en rodajas': 200,
    'rodajas de pepperoni': 100,
    'hojas de albahaca fresca': 100,
    'taza de arándanos frescos': 100,
    'cucharadita de esencia de vainilla': 5,
    'pizca de nuez moscada': 1,
    'pizca de pimienta negra molida': 1,
    'manzanas peladas y en rodajas finas': 200,
    'cucharadita de tomillo seco': 5,
    'tazas de café espresso fuerte, enfriado': 400,
    'tazas de queso mascarpone': 400,
    'tazas de bizcochos de soletilla': 200,
    'cucharadita de cacao en polvo sin azúcar': 5,
    'taza de salsa bechamel': 250,
    'Hierbas italianas secas': 5,
    'limones': 200,
    'cucharadita de pimienta negra molida': 5,
    'cucharadita de paprika': 5,
    'rodajas de limón': 150,
    'hojas de alga nori': 100,
    'taza de arroz sushi cocido y enfriado': 200,
    'aguacate en tiras': 150,
    'salmón ahumado en tiras': 200,
    'taza de pepino en tiras': 150,
    'cucharadita de vinagre de arroz': 5,
    'semillas de sésamo tostadas': 50,
    'salsa de soja para servir': 250,
    'Wasabi': 5,
    'jengibre encurtido para servir': 50,
    'lechuga romana picada': 100,
    'pechuga de pollo a la parrilla en tiras': 200,
    'taza de crotones de pan': 100,
    'aceite de oliva extra virgen': 250,
    'sal y pimienta al gusto': 5,
    'anchoas en aceite': 200,
    'cucharadita de café instantáneo': 5,
    'taza de arroz Arborio': 200,
    'taza de vino blanco seco': 250,
    'ramitas de tomillo fresco': 15,
    'fresas frescas, en rodajas': 100,
    'cucharada de mermelada de fresa': 15,
    'cucharadita de gelatina sin sabor': 5,
    'cucharada de agua': 15,
    'azúcar glas': 100,
    'taza de arroz blanco': 200,
    'cáscara de limón': 200,
    'ramita de canela': 15,
    'pechuga de pollo en tiras': 200,
    'cucharada de harina de trigo': 15,
    'taza de leche evaporada': 400,
    'taza de leche condensada': 400,
    'paquete de pasta spaghetti': 200,
    'taza de panceta o tocino en tiras': 200,
    'sal al gusto': 5,
    'perejil fresco picado para decorar': 5,
    'taza de café espresso, enfriado': 250,
    'taza de queso mascarpone': 400,
    'paquete de bizcochos tipo ladyfingers': 200,
    'cucharada de cacao en polvo sin azúcar': 15,
    'tazas de tomates frescos, picados': 400,
    'zanahoria picada': 200,
    'pizca de sal y pimienta': 1,
    'cucharada de albahaca fresca picada': 15,
    'taza de crema espesa': 250,
    'tomates frescos, en rodajas': 200,
    'bola de queso mozzarella fresco, en rodajas': 200,
    'cucharadas de aceite de oliva extra virgen': 30,
    'cucharada de vinagre balsámico': 15,
    'tomates maduros, pelados y sin semillas': 200,
    'pepino pelado y picado': 150,
    'taza de pan duro, sin corteza y remojado en agua': 200,
    'cucharada de vinagre de vino tinto': 15,
    'cucharada de aceite de oliva extra virgen': 15,
    'pimientos grandes, cortados por la mitad y sin semillas': 200,
    'taza de arroz cocido': 200,
    'taza de tomate triturado': 200,
    'cucharadita de pimentón dulce': 5,
    'taza de arroz sushi': 200,
    'filete de salmón fresco sin piel ni espinas': 200,
    'alga nori': 100,
    'vinagre de arroz': 250,
    'azúcar': 400,
    'sal': 5,
    'vino tinto': 250,
    'wasabi': 5,
    'jengibre encurtido': 50,
    'pasta de ajonjolí tostado': 30,
    'palitos para sushi': 200,
    'tortillas de maíz o harina': 200,
    'carne de res o cerdo en tiras': 200,
    'tomates en cubos': 200,
    'ramitas de cilantro fresco picado': 15,
    'pan de hamburguesa': 200,
    'carne de res molida': 200,
    'queso cheddar en lonchas': 100,
    'hojas de lechuga': 100,
    'rodajas de tomate': 200,
    'cebolla roja en rodajas finas': 200,
    'pepinillos en rodajas': 150,
    'salsa de tomate o kétchup': 250,
    'mostaza': 30,
    'mayonesa': 250,
    'calabacín en cubos': 200,
    'zanahoria en rodajas': 200,
    'patata en cubos': 200,
    'puerro en rodajas': 200,
    'tomate en cubos': 200,
    'caldo de verduras': 1000
}