ingredientes = [
{
  "Tortillas de maíz o harina": 25,
  "Rebanadas de pan de molde": 8,
  "Ramitas de cilantro fresco": 1,
  "Nutella o crema de avellanas": 1,
  "Taza de leche caliente": 250,
  "Hojas de nori": 8,
  "Tazas de zanahoria rallada": 2,
  "Cucharadita de cacao en polvo sin azúcar": 5,
  "Levadura seca activa": 1,
  "Cucharadita de vinagre de arroz": 5,
  "Aguacate en rodajas": 2,
  "Muslos de pollo, troceados": 350,
  "Orégano seco (opcional)": 1,
  "Lata de leche de coco": 400,
  "Taza de arroz cocido": 200,
  "Taza de pasas": 150,
  "Cucharadas de harina de trigo": 50,
  "Taza de arroz sushi cocido y enfriado": 200,
  "Huevo duro picado": 2,
  "Tazas de crema para batir": 1,
  "Cucharadas de licor de café o ron (opcional)": 2,
  "Aguacate en tiras": 2,
  "Lechuga romana lavada y picada": 1,
  "Limones en cuartos para servir": 1,
  "Taza de lechuga romana cortada en trozos": 100,
  "Cucharadas de mantequilla fría cortada en trozos pequeños": 50,
  "Ramitas de perejil fresco picado": 1,
  "Cucharadita de chile en polvo (opcional)": 5,
  "Taza de mozzarella fresca en rodajas": 250,
  "Ramitas de romero fresco": 1,
  "Cucharada de aceite de coco": 15,
  "Queso mozzarella rallado": 250,
  "Taza de salsa de tomate para pizza": 250,
  "Cucharada de miel o edulcorante natural (opcional)": 15,
  "Pizca de sal": 1,
  "Tazas de lentejas secas": 1,
  "Cucharaditas de polvo de hornear": 10,
  "Taza de caldo de pollo caliente": 250,
  "Taza de vino blanco": 250,
  "Taza de salsa bechamel": 250,
  "Pechuga de pollo a la plancha en tiras": 350,
  "Cucharadita de esencia de vainilla": 5,
  "Masa quebrada o masa para tarta": 1,
  "Pimientos grandes, cortados por la mitad y sin semillas": 4,
  "Wasabi para servir": 1,
  "Lata de salsa de enchilada roja": 400,
  "Taza de vinagre de arroz": 250,
  "Taza de crutones de pan tostado": 100,
  "Tazas de café espresso fuerte y frío": 2,
  "Cucharadita de bicarbonato de sodio": 5,
  "Azúcar glas (opcional, para decorar)": 50,
  "Pechugas de pollo cortadas en tiras": 350,
  "Miel o jarabe de arce": 1,
  "Pechuga de pollo a la parrilla en tiras": 350,
  "Taza de café espresso, enfriado": 250,
  "Kiwis pelados y cortados en rodajas": 2,
  "Paquete de bizcochos tipo ladyfingers": 1,
  "Zanahorias en cubos": 2,
  "Tortillas de maíz para tacos": 8,
  "Tomates en cubos": 2,
  "Espaguetis o pasta larga": 250,
  "Palitos para sushi": 8,
  "Cucharada de aceite de oliva extra virgen": 15,
  "Taza de café espresso": 250,
  "Cucharadita de canela molida": 5,
  "Huevos separados (claras y yemas)": 2,
  "Taza de aceite de girasol": 250,
  "Pizca de pimienta negra molida": 1,
  "Huevo": 1,
  "Taza de pasta tipo fettuccine": 250,
  "Queso parmesano rallado": 100,
  "Tomate maduro en rodajas finas": 2,
  "Sal al gusto": 0,
  "Tomates cherry cortados por la mitad": 8,
  "Taza de yogur natural": 250,
  "Taza de pan duro, sin corteza y remojado en agua": 250,
  "Langostinos o gambas peladas": 350,
  "Cucharadita de mostaza dijon": 5,
  "Cucharadita de pimienta negra molida": 5,
  "Mayonesa": 250,
  "Wasabi (opcional, para servir)": 1,
  "Cucharadas de pasta de curry rojo": 2,
  "Carne de res o cerdo en tiras": 350,
  "Kg de tomates maduros": 1,
  "Tazas de harina de trigo": 250,
  "Cucharadita de pimienta negra": 5,
  "Pizca de sal y pimienta negra": 0,
  "Aceite de oliva virgen extra": 250,
  "Yemas de huevo": 2,
  "Taza de queso parmesano rallado": 100,
  "Cebolla grande": 1,
  "Dientes de ajo picados": 2,
  "Pimiento rojo picado": 1,
  "Ramitas de tomillo fresco": 1,
  "Filete de salmón fresco": 350,
  "Taza de crema batida": 250,
  "Litros de caldo de pescado o pollo caliente": 2,
  "Taza de pechuga de pollo a la parrilla en tiras": 350,
  "Aceite vegetal": 250,
  "Limones cortados en cuartos": 1,
  "Huevos separadas las claras de las yemas": 2,
  "Tazas de arroz bomba o arroz de paella": 2,
  "Bola de queso mozzarella fresco, en rodajas": 250,
  "Manzanas verdes peladas y en rodajas": 2,
  "Hojas de lechuga romana": 1,
  "Lechuga romana": 1,
  "Taza de champiñones picados": 250,
  "Taza de arroz blanco": 250,
  "Pimienta": 0,
  "Taza de champiñones en rodajas": 250,
  "Cebolla blanca finamente picada": 1,
  "Taza de crema de queso (para el frosting)": 250,
  "Hojas de lechuga": 1,
  "Cucharada de azúcar glas (opcional, para decorar)": 15,
  "Salsa césar (comprada o casera)": 250,
  "Limón exprimido": 1,
  "Cucharada de mermelada de fresa": 15,
  "Perejil fresco picado para decorar": 1,
  "Salsa de soja (opcional, para servir)": 250,
  "Pan tostado o croutons": 100,
  "Queso parmesano rallado (opcional)": 100,
  "Carne picada (res o ternera)": 350,
  "Alga nori": 8,
  "Taza de caldo de pollo": 250,
  "Pimiento verde picado": 1,
  "Tortillas de maíz": 8,
  "Lata de frijoles refritos": 400,
  "Cucharadas de licor de café (opcional)": 2,
  "Cucharadita de extracto de vainilla": 5,
  "Taza de champiñones frescos rebanados": 250,
  "Caldo de verduras": 250,
  "Pan de hamburguesa": 4,
  "Semillas de sésamo tostadas": 1,
  "Taza de jugo de naranja": 250,
  "Tomate en cubos": 2,
  "Wasabi": 1,
  "Tazas de bizcochos de soletilla": 2,
  "Taza de arroz arborio": 250,
  "Jengibre encurtido (gari)": 1,
  "Cucharadas de mantequilla fría en trozos": 50,
  "Taza de arándanos frescos": 150,
  "Calamares limpios y cortados en anillos": 350,
  "Cucharadita de polvo de hornear": 5,
  "Cebolla picada finamente": 1,
  "Tazas de crutones": 1,
  "Taza de azúcar blanca": 200,
  "Taza de queso ricotta": 250,
  "Hojas frescas de albahaca": 1,
  "Taza de cilantro fresco picado": 250,
  "Lata de leche evaporada": 100,
}
]