ingredientes = [
  {
    "tortillas": 25,
    "pan-molde": 8,
    "cilantro": 15,
    "nutella": 15,
    "leche": 250,
    "hojas-nori": 8,
    "zanahoria": 10,
    "cacao": 5,
    "levadura": 5,
    "vinagre-de-arroz": 5,
    "aguacate": 30,
    "pollo-trozos": 350,
    "orégano-seco": 5,
    "leche-coco": 400,
    "arroz": 200,
    "pasas": 10,
    "harina-trigo": 50,
    "arroz-cocido": 200,
    "huevo-picado": 15,
    "crema-de-leche": 250,
    "licor-café": 30,
    "lechuga-romana": 100,
    "limon": 15,
    "mantequilla": 50,
    "perejil": 15,
    "chile-en-polvo": 5,
    "mozzarella": 250,
    "romero": 15,
    "aceite-de-coco": 15,
    "queso-mozzarella": 250,
    "salsa-de-tomate": 250,
    "miel": 15,
    "sal": 10,
    "lentejas": 100,
    "polvo-de-hornear": 100,
    "caldo-de-pollo": 250,
    "vino-blanco": 250,
    "salsa-bechamel": 250,
    "esencia-de-vainilla": 5,
    "masa-para-tarta": 100,
    "Pimientos-grandes": 4,
    "salsa-de-enchilada-roja": 400,
    "pan-tostado": 100,
    "café-espresso": 200,
    "Cucharadita de bicarbonato de sodio": 15,
    "Azúcar glas": 50,
    "Miel o jarabe de arce": 100,
    "Pechuga de pollo a la parrilla en tiras": 350,
    "Taza de café espresso, enfriado": 250,
    "Kiwis pelados y cortados en rodajas": 30,
    "Paquete de bizcochos tipo ladyfingers": 10,
    "Tomates en cubos": 200,
    "Espaguetis o pasta larga": 250,
    "Palitos para sushi": 10,
    "Cucharada de aceite de oliva extra virgen": 15,
    "Taza de café espresso": 250,
    "Cucharadita de canela molida": 5,
    "Huevos separados (claras y yemas)": 15,
    "Taza de aceite de girasol": 250,
    "Pizca de pimienta negra molida": 2,
    "Huevo": 50,
    "Taza de pasta tipo fettuccine": 250,
    "Queso parmesano rallado": 100,
    "Tomate maduro en rodajas finas": 2,
    "Sal al gusto": 10,
    "Tomates cherry cortados por la mitad": 8,
    "Taza de yogur natural": 250,
    "Taza de pan duro, sin corteza y remojado en agua": 250,
    "Langostinos o gambas peladas": 350,
    "Cucharadita de mostaza dijon": 2,
    "Cucharadita de pimienta negra molida": 30,
    "Mayonesa": 15,
    "Cucharadas de pasta de curry rojo": 30,
    "Carne de res o cerdo en tiras": 350,
    "Kg de tomates maduros": 1000,
    "Tazas de harina de trigo": 250,
    "Cucharadita de pimienta negra": 5,
    "Pizca de sal y pimienta negra": 2,
    "Aceite de oliva virgen extra": 250,
    "Yemas de huevo": 20,
    "Taza de queso parmesano rallado": 100,
    "Cebolla grande": 300,
    "Dientes de ajo picados": 2,
    "Pimiento rojo picado": 120,
    "Ramitas de tomillo fresco": 1,
    "Filete de salmón fresco": 350,
    "Taza de crema batida": 250,
    "Litros de caldo de pescado o pollo caliente": 2000,
    "Taza de pechuga de pollo a la parrilla en tiras": 350,
    "Aceite vegetal": 250,
    "Limones cortados en cuartos": 50,
    "Huevos separadas las claras de las yemas": 2,
    "Tazas de arroz bomba o arroz de paella": 2,
    "Bola de queso mozzarella fresco, en rodajas": 250,
    "Manzanas verdes peladas y en rodajas": 2,
    "Hojas de lechuga romana": 1,
    "Lechuga romana": 300,
    "Taza de champiñones picados": 250,
    "Taza de arroz blanco": 250,
    "Pimienta": 0.3,
    "Taza de champiñones en rodajas": 250,
    "Cebolla blanca finamente picada": 1,
    "Taza de crema de queso (para el frosting)": 250,
    "hojas-lechuga": 3,
    "azúcar-glas": 15,
    "Salsa césar (comprada o casera)": 250,
    "Limón exprimido": 20,
    "Cucharada de mermelada de fresa": 15,
    "Perejil fresco picado para decorar": 15,
    "Salsa de soja": 250,
    "Pan tostado o croutons": 100,
    "Queso parmesano rallado": 100,
    "Carne picada (res o ternera)": 350,
    "Alga nori": 8,
    "Taza de caldo de pollo": 250,
    "Pimiento verde picado": 120,
    "Lata de frijoles refritos": 400,
    "Cucharadas de licor de café": 30,
    "Cucharadita de extracto de vainilla": 5,
    "Taza de champiñones frescos rebanados": 250,
    "Caldo de verduras": 250,
    "Pan de hamburguesa": 80,
    "Semillas de sésamo tostadas": 1,
    "Taza de jugo de naranja": 250,
    "Tomate en cubos": 5, 
    "Wasabi": 5,
    "Tazas de bizcochos de soletilla": 2,
    "Taza de arroz arborio": 250,
    "Jengibre encurtido (gari)": 15,
    "Cucharadas de mantequilla fría en trozos": 50,
    "Taza de arándanos frescos": 150,
    "Calamares limpios y cortados en anillos": 350,
    "Cucharadita de polvo de hornear": 5,
    "Cebolla picada finamente": 10,
    "Tazas de crutones": 30,
    "azúcar-blanca": 200,
    "queso-ricotta": 250,
    "albahaca": 16,
    "leche-evaporada": 400
  }
]